sonata_admin:
    title: 'Company Calendar'
    title_logo: 'assets/imgs/calendar.png'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        layout: 'standard.html.twig'
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
